"""Slop vocabulary: words and phrases statistically overrepresented in LLM output.

Sources: slop-forensics (Sam Paech), EQ-Bench Slop Score, NousResearch ANTI-SLOP.md.
"""

from __future__ import annotations

# Tier 1: extreme overrepresentation (10-100x vs human baseline).
# Single words — matched case-insensitively as whole words.
SLOP_WORDS: frozenset[str] = frozenset(
    {
        "delve",
        "delving",
        "delved",
        "utilize",
        "utilizing",
        "utilized",
        "utilization",
        "facilitate",
        "facilitating",
        "facilitated",
        "elucidate",
        "elucidating",
        "elucidated",
        "embark",
        "embarking",
        "embarked",
        "endeavor",
        "endeavors",
        "endeavour",
        "encompass",
        "encompasses",
        "encompassing",
        "multifaceted",
        "tapestry",
        "testament",
        "paradigm",
        "synergy",
        "synergies",
        "holistic",
        "catalyze",
        "catalyzing",
        "juxtapose",
        "juxtaposition",
        "nuanced",
        "myriad",
        "plethora",
        "pivotal",
        "groundbreaking",
        "cutting-edge",
        "game-changer",
        "game-changing",
        "spearhead",
        "spearheading",
        "underscores",
        "underscoring",
        "leveraging",
        "leveraged",
        "streamline",
        "streamlining",
        "streamlined",
        "overarching",
        "cornerstone",
        "cornerstones",
        "aforementioned",
        "henceforth",
        "noteworthy",
        "commendable",
        "meticulous",
        "meticulously",
        "intricate",
        "intricacies",
        "aligns",
        "aligning",
        "resonates",
        "resonate",
        "resonating",
        "bustling",
        "moreover",
        "furthermore",
        "nevertheless",
        "nonetheless",
        "harnessing",
        "harness",
        "harnessed",
        "bolster",
        "bolstering",
        "bolstered",
        "fostering",
        "fostered",
        "captivating",
        "captivated",
        "interplay",
        "wholesome",
        "reinvigorate",
    }
)

# Tier 2: multi-word patterns matched via substring (lowercased).
SLOP_PHRASES: tuple[str, ...] = (
    "it's important to note",
    "it is important to note",
    "it's worth noting",
    "it is worth noting",
    "in today's world",
    "in today's fast-paced",
    "in the realm of",
    "in the landscape of",
    "dive into",
    "diving into",
    "deep dive",
    "let's delve",
    "let's explore",
    "not just a",
    "isn't just about",
    "is not just about",
    "at its core",
    "at the end of the day",
    "in conclusion",
    "stands as a testament",
    "serves as a testament",
    "it's crucial to",
    "it is crucial to",
    "navigating the",
    "navigate the complexities",
    "the intricacies of",
    "a comprehensive guide",
    "the ultimate guide",
    "everything you need to know",
    "here's what you need to know",
    "here is what you need to know",
    "whether you're a",
    "look no further",
    "unlock the power",
    "unlock the potential",
    "unlock the secrets",
    "elevate your",
    "take it to the next level",
    "revolutionize your",
    "transform your",
    "game-changing",
    "ever-evolving",
    "ever-changing",
    "in this article, we",
    "in this blog post",
    "without further ado",
    "buckle up",
    "in an era where",
    "in a world where",
)

# Transition words that AI tends to start paragraphs with.
TRANSITION_STARTS: frozenset[str] = frozenset(
    {
        "additionally",
        "furthermore",
        "moreover",
        "consequently",
        "subsequently",
        "nevertheless",
        "nonetheless",
        "conversely",
        "specifically",
        "importantly",
        "significantly",
        "ultimately",
        "essentially",
        "fundamentally",
        "interestingly",
        "remarkably",
        "notably",
        "meanwhile",
    }
)
